<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Summary" data-toc-modified-id="Summary-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Types" data-toc-modified-id="Types-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Types</a></span><ul class="toc-item"><li><span><a href="#Atomic-types" data-toc-modified-id="Atomic-types-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Atomic types</a></span></li><li><span><a href="#Operators" data-toc-modified-id="Operators-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Operators</a></span></li><li><span><a href="#Lists-(a-container)" data-toc-modified-id="Lists-(a-container)-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Lists (a container)</a></span></li><li><span><a href="#Tuples-(another-container)" data-toc-modified-id="Tuples-(another-container)-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Tuples (another container)</a></span></li><li><span><a href="#Dictionaries-(a-keyword-container)" data-toc-modified-id="Dictionaries-(a-keyword-container)-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Dictionaries (a keyword container)</a></span></li></ul></li><li><span><a href="#Classes-(user-defined-types)" data-toc-modified-id="Classes-(user-defined-types)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Classes (user-defined types)</a></span></li><li><span><a href="#Conditionals-and-loops" data-toc-modified-id="Conditionals-and-loops-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Conditionals and loops</a></span><ul class="toc-item"><li><span><a href="#Conditionals" data-toc-modified-id="Conditionals-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Conditionals</a></span></li><li><span><a href="#Simple-loops" data-toc-modified-id="Simple-loops-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Simple loops</a></span></li><li><span><a href="#Itertools" data-toc-modified-id="Itertools-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Itertools</a></span></li><li><span><a href="#Dictionaries" data-toc-modified-id="Dictionaries-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Dictionaries</a></span></li><li><span><a href="#List-comprehensions" data-toc-modified-id="List-comprehensions-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>List comprehensions</a></span></li><li><span><a href="#Iterator" data-toc-modified-id="Iterator-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Iterator</a></span></li></ul></li><li><span><a href="#Functions" data-toc-modified-id="Functions-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Functions</a></span><ul class="toc-item"><li><span><a href="#Baseline" data-toc-modified-id="Baseline-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Baseline</a></span></li><li><span><a href="#A-function-is-an-object" data-toc-modified-id="A-function-is-an-object-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>A function is an object</a></span></li><li><span><a href="#Scope" data-toc-modified-id="Scope-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Scope</a></span></li><li><span><a href="#Recursion" data-toc-modified-id="Recursion-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Recursion</a></span></li></ul></li><li><span><a href="#Floating-point-numbers" data-toc-modified-id="Floating-point-numbers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Floating point numbers</a></span></li><li><span><a href="#Numpy" data-toc-modified-id="Numpy-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Numpy</a></span></li><li><span><a href="#Export-to-HTML" data-toc-modified-id="Export-to-HTML-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Export to HTML</a></span></li></ul></div>

# Summary

You will be given an in-depth introduction to the **fundamentals of Python** (objects, variables, operators, classes, methods, functions, conditionals, loops). You learn to discriminate between different **types** such as integers, floats, strings, lists, tuples and dictionaries, and determine whether they are **subscriptable** (slicable) and/or **mutable**. You will learn about **referencing** and **copying**. You will learn a tiny bit about **floating point arithmetics**.

**Links**:

- **tutorial**: [link](https://www.python-course.eu/python3_course.php) (detailed)

- **numpy**: [link](https://www.python-course.eu/numpy.php)


# Types

All **variables** in Python is a **reference** to an **object** of some **type**.

## Atomic types

**Integers:**

In [1]:
x = 1 # variable x reference an integer type object with a value of 1
print(type(x)) # prints the type of x
print(x) # prints the value of x

<class 'int'>
1


**Floats**:

In [2]:
x = 1.2 # variable x reference an floating point (decimal number) type object with a value of 1.2 
print(type(x))
print(x)

<class 'float'>
1.2


**Strings**:

In [3]:
x = 'abc' # variable x reference a string type opbject with a value of 'abc'
print(type(x))
print(x)

<class 'str'>
abc


**Booleans**:

In [4]:
x = False # variable x reference a boolean type opbject with a value of False
print(type(x))
print(x)

<class 'bool'>
False


Objects of one type can (sometimes) be **converted** into another type. E.g. from float to string:

In [5]:
x = 1.2  # variable x reference an floating point (decimal number) type object with a value of 1.2 
x = str(x)  # variable x now reference a string type object with a value created based on x 
print(type(x))
print(x)

<class 'str'>
1.2


or from float to integer:

In [6]:
x = 1.2
x = int(x) # variable x now reference an integer type object with a value created based on x 
print(type(x))
print(x)

<class 'int'>
1


**Note:** You can e.g. not convert a string into an integer raises an error,

In [7]:
try: # try to run this block
    x = int('abc')
    print('can be done')
except: # if any error found run this block instead
    print('cannot be done')

cannot be done


## Operators

Variables can be combined using **operators** (e.g. +, -, /, **)

In [8]:
# numbers
x = 3
y = 2
print(x+y)
print(x-y)
print(x/y)
print(x*y)
print(x**y)

5
1
1.5
6
9


In [9]:
# strings
x = 'abc'
y = 'def'
print(x+y)

abcdef


In [10]:
# strings and integers
x = 'abc'
y = 2
print(x*y)

abcabc


Variables can be changed using **augmented operators** (e.g. +=,-=,/=)

In [11]:
x = 3
print(x)
x += 1 
print(x)
x *= 2 
print(x)
x /= 2 
print(x)

3
4
8
4.0


Variables can be compared using **boolean operators** (e.g. <, <=, >, >=, !=, ==)

In [12]:
x = 3
y = 2
print(x < y)
print(x <= y)
print(x != y)
print(x == y)

False
False
True
False


## Lists (a container)

Python also have **containers** (also called **collection types**). A first example is a **list**.  A list contains **variables** each **referencing** to some **object**.

In [13]:
x = [1,'abc'] # variable x reference a list type opbject with elements referencing 1 and 'abc'
print(type(x))
print(x) # prints the contens of the list

<class 'list'>
[1, 'abc']


The **length** of a list can be found with the **len** function.

In [14]:
print(len(x))

2


A list is **subscriptable** starting from **index 0**.

In [15]:
print(x[0])
print(x[1])

1
abc


A list is **mutable**, i.e. you can change its elements on the fly.

In [16]:
x[0] = 2
x[1] = 'def'
print(x)

[2, 'def']


and add more elements

In [17]:
x.append('new_element') # add new element to end of list
print(x)

[2, 'def', 'new_element']


A list is **slicable**, i.e. you can exact a list from a list 

In [18]:
x = [0,1,2,3,4,5]
print(x[0:3])
print(x[1:3])
print(x[1:-1])
print(x[:3])

[0, 1, 2]
[1, 2]
[1, 2, 3, 4]
[0, 1, 2]


**Important**: Multiple variables can refer to the **same** list. 

In [19]:
x = [1,2,3]
y = x # y now reference the same list of references as x
y[0] = 2 # change the first element in the list y references
print(x) # x is also changed because it references the same list as y

[2, 2, 3]


If one variable is deleted, the other one still reference the list.

In [20]:
del x # delete the variable x
print(y)

[2, 2, 3]


Alternatively, lists can by **copied** by using the copy-module:

In [21]:
from copy import copy

x = [1,2,3]
y = copy(x) # y now a copy y 
y[0] = 2
print(x)

[1, 2, 3]


or by slicing:

In [22]:
x = [1,2,3]
y = x[:]
y[0] = 1
print(x)

[1, 2, 3]


A **deepcopy** is necessary, when the list contains mutable objects.

In [23]:
from copy import deepcopy

x = [[1,2,3],2,3]
y1 = copy(x) # y1 now a copy x
y2 = x[:] # y2 is now another copy of x
y3 = deepcopy(x) # y3 is a deep copy

x[0][0] = 2
x[1] = 1
print(x)
print(y1)
print(y2)
print(y3)

[[2, 2, 3], 1, 3]
[[2, 2, 3], 2, 3]
[[2, 2, 3], 2, 3]
[[1, 2, 3], 2, 3]


## Tuples (another container)

A **tuple** is an **immutable list**.

In [24]:
a = (1,2,3)
print(a[0])
try: # try to run this block
    a[0] = 2
    print('did succeed in setting a[0]=2')
except: # if any error found run this block instead
    print('dit NOT succeed in setting a[0]=2')
print(a)

1
dit NOT succeed in setting a[0]=2
(1, 2, 3)


## Dictionaries (a keyword container)

A **dictionary** is a **keyword-based** (instead of index-based) container. All immutable objects can be used as keywords. Values are unrestricted. Dictionaries can be extended on the fly:

In [25]:
x = {} # create x as an empty dictionry
x['abc'] = '1' # keywrod='abc', value = '1'
x[('abc',1)] = 2 # keywrod=('abc',1), value = '1'

In [26]:
y = {'abc': '1'} # create y as an dictionary with key-value-pair ('abc','1')

Elements of a dictionary are **extracted** using their keyword: 

In [27]:
print(x['abc'])

1


# Classes (user-defined types)

New types of objects can be defined using **classes**.

In [28]:
# a. define a new type of object called a consumer
class consumer():
    
    def __init__(self,name,height,weight):
        
        self.name = name # an attribute
        self.height = height # an attribute
        self.weight = weight # an attribute
    
    def bmi(self): # a method
        bmi = self.weight/(self.height/100)**2 # calculate bmi
        return bmi # output bmi 
        
# b. create an instance of the consumer object called "jeppe"        
jeppe = consumer('jeppe',182,80) # height=182, weight=80

# c. print an attribute
print(jeppe.name)

# d. print the result of calling a method
print(jeppe.bmi())

jeppe
24.151672503320853


**Attributes** can be changed and extracted with **.-notation**

In [29]:
jeppe.height = 160
print(jeppe.height)
print(jeppe.bmi())

160
31.249999999999993


Or with **setattr- and getatrr-notation**

In [30]:
setattr(jeppe,'height',182)
height = getattr(jeppe,'height')
print(height)
print(jeppe.bmi())

182
24.151672503320853


If the **appropriate methods** are defined, standard operators, e.g. +, and general functions such as print can be used.

In [31]:
# a. define a new type of object called a fraction
class fraction:
    
    def __init__(self,nominator,denominator):
        self.nom = nominator
        self.denom = denominator
    
    def __str__(self): # called when using print
        return f'{self.nom}/{self.denom}'
    
    def __add__(self,other): # called when using +
        
        new_nom = self.nom*other.denom + self.nom*other.denom
        new_denom = self.denom*other.denom
        return fraction(new_nom,new_denom)

# b. create an instance of the fraction object  
x = fraction(1,3)
print(type(x))
print(x)

# c. create another instance of the fraction object
y = fraction(2,4)
print(type(y))
print(y)

# d. add them together
print('')
print(x+y)

<class '__main__.fraction'>
1/3
<class '__main__.fraction'>
2/4

8/12


# Conditionals and loops

## Conditionals

You typically want your program to do one thing if some condition is met, and another thing if another condition is met. In Python this is done with **conditional statments**:

In [32]:
x = 2
if x < 2: 
    # happens if x is smaller than 2
    print('first possibility')
elif x > 4:
    # happens if x is not smaller than 2 and x is larger than 4
    print('second possibility')
elif x < 0:
    # happens if x is not smaller than 2, x is not larger than 4
    #  and x is smaller than 0
    print('third posibility') # note: this can never happen
else:
    # happens if x is not smaller than 2, x is not larger than 4
    #  and x is not smaller than 0
    print('fourth possiblity')  

fourth possiblity


Note that:

1. "elif" is short for "else if" 
2. the **indentation** after if, elif and else is required 

An **equivalent formulation** of the above if-elif-else statement is:

In [33]:
x = 2
cond_1 = x < 2 # a boolean (true or false)
cond_2 = x > 4 # a boolean (true or false)
cond_3 = x < 0 # a boolean (true or false)
if cond_1: 
    print('first possibility')
elif cond_2:
    print('second possibility')
elif cond_3:
    print('third posibility') # note: this can never happen
else:
    print('fourth possiblity')

fourth possiblity


## Simple loops

It is time-consuming to write: 

In [34]:
x_list = [1,2,3,4,5]
y_list = []
y_list.append(x_list[0]**2)
y_list.append(x_list[1]**2)
y_list.append(x_list[2]**2)
y_list.append(x_list[3]**2)
y_list.append(x_list[4]**2)
print(y_list)

[1, 4, 9, 16, 25]


Use a **for loop** instead

In [35]:
y_list = []
for x in x_list:
    y_list.append(x**2)
print(y_list)

[1, 4, 9, 16, 25]


Or a **while loop**:

In [36]:
y_list = []
i = 0
while i <= 3:
    y_list.append(x_list[i]**2)
    i += 1

For loops can also be **enumerated**

In [37]:
y_list = []
for i,x in enumerate(x_list):
    y_list.append((i,x**2))
print(y_list)

[(0, 1), (1, 4), (2, 9), (3, 16), (4, 25)]


Loops can be fine-tuned with **continue** and **break**

In [38]:
y_list = []
for i,x in enumerate(x_list):
    if i == 1:
        continue # go to next iteration 
    elif i == 4:
        break # stop loop prematurely
    y_list.append((i,x**2))
print(y_list)

[(0, 1), (2, 9), (3, 16)]


## Itertools

In [39]:
import itertools as it

x = ['I', 'II', 'II']
y = ['a', 'b', 'c']

for i,j in zip(x,y):
    print((i,j))

('I', 'a')
('II', 'b')
('II', 'c')


In [40]:
for i,j in it.product(x,y):
    print((i,j))

('I', 'a')
('I', 'b')
('I', 'c')
('II', 'a')
('II', 'b')
('II', 'c')
('II', 'a')
('II', 'b')
('II', 'c')


In [41]:
for k,(i,j) in enumerate(it.product(x,y)):
    print((k,i,j))

(0, 'I', 'a')
(1, 'I', 'b')
(2, 'I', 'c')
(3, 'II', 'a')
(4, 'II', 'b')
(5, 'II', 'c')
(6, 'II', 'a')
(7, 'II', 'b')
(8, 'II', 'c')


In [42]:
for k,((k1,i),(k2,j)) in enumerate(it.product(enumerate(x),enumerate(y))):
    print((k,k1,k2,i,j))

(0, 0, 0, 'I', 'a')
(1, 0, 1, 'I', 'b')
(2, 0, 2, 'I', 'c')
(3, 1, 0, 'II', 'a')
(4, 1, 1, 'II', 'b')
(5, 1, 2, 'II', 'c')
(6, 2, 0, 'II', 'a')
(7, 2, 1, 'II', 'b')
(8, 2, 2, 'II', 'c')


## Dictionaries

You can loop throug keys, values or key-value pairs of a dictionary.

In [43]:
my_dict = {'a': '-', 'b': '--', 'c': '---'}
for key in my_dict.keys():
    print(key)
print('')
for val in my_dict.values():
    print(val)
print('')
for key,val in my_dict.items():
    print((key,val))

a
b
c

-
--
---

('a', '-')
('b', '--')
('c', '---')


## List comprehensions

You can get a list in a loop:

In [44]:
my_list = []
for x in range(10):
    my_list.append(x**2)
print(my_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


or with a list comprehension:

In [45]:
my_list = [x**2 for x in range(10)]
print(my_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


## Iterator

Consider the following loop, where my_list is said to be **iterable**.

In [46]:
my_list = [0,2,4,6,8]
for i in my_list:
    print(i)

0
2
4
6
8


Consider the same loop generatored with a **iterator** 

In [47]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


which can also be written

In [48]:
x = iter(range(0,10,2))
print(x)
print(next(x))
print(next(x))
print(next(x))

0
2
4


The main benefit here is that the, potentially long my_list, is never created

We can also write **our own iterator class**:

In [49]:
class range_two_step:
    
    def __init__(self, N):
        self.i = 0
        self.N = N
        
    def __iter__(self):
        return self
    
    def __next__(self):
        
        if self.i >= self.N:
            raise StopIteration
        
        temp = self.i
        self.i = self.i + 2
        return temp 

# a. create an iterator from the class
x = iter(range_two_step(10))
print(next(x))
print(next(x))
print(next(x))
print('')

# b. use it in a loop
for i in range_two_step(10):
    print(i)

0
2
4

0
2
4
6
8


# Functions

## Baseline

One input, one output:

In [50]:
def f(x):
    return x**2

print(f(2))

4


Two input, one output:

In [51]:
def f(x,y):
    return x**2 + y**2

print(f(2,2))

8


Two input, two output:

In [52]:
def f(x,y):
    z = x**2
    q = y**2
    return z,q

print(f(2,2))

(4, 4)


Undefined number of inputs:

In [53]:
def f(*args):
    out = 0
    for x in args:
        out += x**2
    return out
print(f(2,2))
print(f(2,2,2,2))

8
16


Keyword inputs:

In [54]:
def f(*args,a=2):
    out = 0
    for x in args:
        out += x**a
    return out
print(f(2,2))
print(f(2,2,a=3))

8
16


Undefined keyword inputs:

In [55]:
def g(**kwargs):
    for key, value in kwargs.items():
        print((key,value))

g(a='abc',b='2',c=[1,2,3])

('a', 'abc')
('b', '2')
('c', [1, 2, 3])


## A function is an object

In [56]:
# a. standard formulation
def f(x):
    return x**2

# b. lambda formulation
g = lambda x: x**2

# c. new reference to same function
h = f

print(f(2))
print(g(2))
del f
print(h(2))

4
4
4


## Scope

In [57]:
a = 2
def f(x):
    return x**a # a is implicitely global

def g(x,a=a):
    return x**a # a default value is fixed when the function is defined

def h(x):
    a = 4 # a is local
    return x**a

def w(x):
    global a # a is explicitely global
    return x**a

print((f(2),g(2),h(2),w(2)))
a += 1
print((f(2),g(2),h(2),w(2)))

(4, 4, 16, 4)
(8, 4, 16, 8)


## Recursion

In [58]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)
    
for i in range(10):
    print(fib(i))

0
1
1
2
3
5
8
13
21
34


# Floating point numbers

There are uncountable many real numbers. On a computer the real line is approximated with numbers on the form:

$$ \text{number} = \text{significant} \times \text{base}^{exponent} $$

* **sign**: 1 bit, positive or negative (positive or negative)
* **exponent**: 11 bits
* **signifcant**: 52 bits

All numbers is therefore not represented, but a *close* neighboring point is used.

In [59]:
x = 0.1
print(f'{x:.100f}') # printing x with 100 decimals
x = 17.1
print(f'{x:.100f}') # printing x with 100 decimals

0.1000000000000000055511151231257827021181583404541015625000000000000000000000000000000000000000000000
17.1000000000000014210854715202003717422485351562500000000000000000000000000000000000000000000000000000


Simple sums might consequently, not be exactly what you expect.

In [60]:
print(0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1 + 0.1)

0.9999999999999999


In [61]:
print(0.1 + 0.2)

0.30000000000000004


In [62]:
1.13 - 1.1

0.029999999999999805

In [63]:
a = 1
print(a+1e-13)
print(a+1e-14)
print(a+1e-15)
print(a+1e-16)

1.0000000000001
1.00000000000001
1.000000000000001
1.0


**Comparisions of floating point numbers** is therefore always problematic

In [64]:
(0.001*1000) / (11.11*1000) == 0.001 / 11.11

False

Multiplying many small numbers can result in an exact zero (**underflow**)

In [65]:
x = 1e-60
y = x
print(y)
y *= x
print(y)
y *= x
print(y)
y *= x
print(y)
y *= x
print(y)
y *= x
print(y)
y *= x

1e-60
1e-120
1e-180
1e-240
9.999999999999999e-301
0.0


If products or sums become too big, they can no longer be represented, and the final result may be wrong or not possible to calculate

In [66]:
x = 1.0
y = 2.7
for j in [1,10,20,40,80,120,160,200]:
    i = 1.0
    while i < j:
        x *= i
        y *= i
        i += 1
    print(f'{j:3d},{y/x:.30f}') # should by 2.0

  1,2.700000000000000177635683940025
 10,2.700000000000000621724893790088
 20,2.700000000000001065814103640150
 40,2.700000000000001953992523340276
 80,2.700000000000001509903313490213
120,nan
160,nan
200,nan


# Numpy

In [68]:
import numpy as np # import the numpy module

A **numpy array** is a **list with homogenous elements**.

Arrays have one or **multiple dimensions**:

In [85]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # on dimension
B = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]]) # two dimensions

print((A.size,B.size))
print((A.ndim,B.ndim))
print((A.shape,B.shape))

(10, 9)
(1, 2)
((10,), (3, 3))


Memory is structured in **rows**.

In [88]:
# a. printing row-by-row
print('row-by-row')
for i in range(B.shape[0]):
    print(B[i,:])
    for j in range(B.shape[1]):
        print((B[i,j],B[i][j]))
    print('')

# b. printin element-by-element
print('element-by-element')
for i in range(B.size):
    print(B.ravel()[i])

row-by-row
[3.4 8.7 9.9]
(3.4, 3.4)
(8.7, 8.7)
(9.9, 9.9)

[ 1.1 -7.8 -0.7]
(1.1, 1.1)
(-7.8, -7.8)
(-0.7, -0.7)

[ 4.1 12.3  4.8]
(4.1, 4.1)
(12.3, 12.3)
(4.8, 4.8)

element-by-element
3.4
8.7
9.9
1.1
-7.8
-0.7
4.1
12.3
4.8


When slicing a numpy array, a **view** is returned.

In [79]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
B = A.copy() # a copy of A
C = A[2:6] # a view into A
C[0] = 0
C[1] = 0
print(A) # changed
print(B) # not changed

[0 1 0 0 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


New arrays can be **created directly**, and be forced to be of integers.

In [80]:
A = np.empty((3,5)) # floats
B = np.empty((3,5),dtype=np.int32) # inters (32-bit)

Standard **mathematical operations** can be applied.

In [89]:
A = np.array([[1,0],[0,1]])
B = np.array([[2,2],[2,2]])
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A@B) # matrix product

[[3 2]
 [2 3]]
[[-1 -2]
 [-2 -1]]
[[2 0]
 [0 2]]
[[0.5 0. ]
 [0.  0.5]]
[[2 2]
 [2 2]]


If arrays does not fit **broadcasting** is applied.

In [83]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
print('multiplication with broadcasting:')
print(A * B)
print('addition with broadcasting:')
print(A + B)

Multiplication with broadcasting: 
[[11 24 39]
 [21 44 69]
 [31 64 99]]
... and now addition with broadcasting: 
[[12 14 16]
 [22 24 26]
 [32 34 36]]


Indexes can be **logical**

In [96]:
A = np.array([1,2,3,4])
B = np.array([3,3,3,3])
I = (A < 3) & (B == 3)
J = (A < 3) & (B == 4)
print(A[I])
print(A[J])

[1 2]
[]


**Methods** to know:

- size / ndim / shape
- ravel / reshape
- copy

**Functions** to know:

- linspace
- array / empty / zeros / ones
- mean / median / std / var / sum
- min/max, amin/amax / fmin/fmax / sort
- meshgrid / hstack / vstack / concatenate / tile

**Concepts** to know:

- view vs. copy
- broadcasting
- logical indexing

# Export to HTML

In [ ]:
import os
os.system('jupyter nbconvert --to html "Optimize_Print_and_Plot.ipynb"')